# Generated by Django 5.2.12 on 2026-04-10 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial_quiz_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='transcript',
            field=models.TextField(blank=True, default=''),
        ),
    ]
